spring:
  application:
    name: springboot2-essentials
  datasource:
    url: jdbc:mysql://localhost:3306/usuario?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update